/**
 * @file main.c
 * @brief Main application entry point for Secure IoT Sensor Node
 * 
 * This file contains the main application initialization, FreeRTOS task
 * creation, and system startup procedures for the STM32-based IoT sensor
 * node with production-quality error handling and safety features.
 * 
 * @author Secure IoT Team
 * @date 2026
 * @version 1.0.0
 */

#include "main.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "stm32f4xx_hal.h"
#include "sensor_task.h"
#include "comm_task.h"
#include "storage_task.h"
#include "update_task.h"
#include "web_interface.h"
#include "led_manager.h"
#include "performance_monitor.h"
#include "system_config.h"
#include <stdint.h>
#include <stdbool.h>

/* ── Configuration Constants ────────────────────────────────────── */

#define MAIN_SYSTEM_CLOCK_HZ         168000000U  /**< System clock frequency */
#define MAIN_TICK_FREQ_HZ             1000U        /**< FreeRTOS tick frequency */
#define MAIN_STARTUP_DELAY_MS         100U         /**< Startup delay in ms */
#define MAIN_MAX_INIT_RETRIES         3U           /**< Maximum initialization retries */

/* Local configuration - these should be moved to system_config.h in production */
#define MAIN_WEB_TASK_PRIORITY        (tskIDLE_PRIORITY + 2U)

/* Stack sizes - verified with high-water mark monitoring */
#define MAIN_SENSOR_TASK_STACK_SIZE   256U         /**< Sensor task stack size */
#define MAIN_WEB_TASK_STACK_SIZE      512U         /**< Web interface task stack size */

/* Queue configuration */
#define MAIN_SENSOR_QUEUE_DEPTH       5U           /**< Sensor data queue depth */
#define MAIN_UART_QUEUE_DEPTH         10U          /**< UART receive queue depth */

/* ── Static Data and Handles ─────────────────────────────────── */

/** FreeRTOS objects */
static QueueHandle_t s_sensor_queue = NULL;
static QueueHandle_t s_uart_rx_queue = NULL;
static SemaphoreHandle_t s_uart_mutex = NULL;

/** Task handles */
static TaskHandle_t s_sensor_task_handle = NULL;
static TaskHandle_t s_web_task_handle = NULL;

/** System state */
static volatile bool s_system_initialized = false;

/* ── Static Function Declarations ───────────────────────────────── */

static bool main_init_hardware(void);
static bool main_init_freertos_objects(void);
static bool main_create_tasks(void);
static void main_error_handler(const char *const pError);
static void main_start_scheduler(void);
static void main_cleanup_resources(void);

/* ── Hardware Initialization ───────────────────────────────────── */

/**
 * @brief Initialize hardware peripherals
 * @return true if successful, false otherwise
 */
static bool main_init_hardware(void)
{
    HAL_StatusTypeDef hal_status;
    
    /* Initialize HAL library */
    hal_status = HAL_Init();
    if (hal_status != HAL_OK) {
        main_error_handler("HAL_Init failed");
        return false;
    }
    
    /* Configure the system clock */
    SystemClock_Config();
    
    /* Initialize all configured peripherals */
    /* In production, these would be generated by STM32CubeMX */
    /*
    hal_status = MX_GPIO_Init();
    if (hal_status != HAL_OK) {
        main_error_handler("GPIO_Init failed");
        return false;
    }
    
    hal_status = MX_I2C1_Init();
    if (hal_status != HAL_OK) {
        main_error_handler("I2C1_Init failed");
        return false;
    }
    
    hal_status = MX_USART1_UART_Init();
    if (hal_status != HAL_OK) {
        main_error_handler("USART1_Init failed");
        return false;
    }
    */
    
    return true;
}

/* ── FreeRTOS Objects Initialization ───────────────────────────── */

/**
 * @brief Initialize FreeRTOS objects
 * @return true if successful, false otherwise
 */
static bool main_init_freertos_objects(void)
{
    /* Create sensor data queue */
    s_sensor_queue = xQueueCreate(MAIN_SENSOR_QUEUE_DEPTH, sizeof(FullSensorData_t));
    if (s_sensor_queue == NULL) {
        main_error_handler("Sensor queue creation failed");
        return false;
    }
    
    /* Create UART receive queue */
    s_uart_rx_queue = xQueueCreate(MAIN_UART_QUEUE_DEPTH, sizeof(uint8_t));
    if (s_uart_rx_queue == NULL) {
        main_error_handler("UART queue creation failed");
        return false;
    }
    
    /* Create UART mutex for thread-safe access */
    s_uart_mutex = xSemaphoreCreateMutex();
    if (s_uart_mutex == NULL) {
        main_error_handler("UART mutex creation failed");
        return false;
    }
    
    return true;
}

/* ── Task Creation ───────────────────────────────────────────── */

/**
 * @brief Create application tasks
 * @return true if successful, false otherwise
 */
static bool main_create_tasks(void)
{
    BaseType_t result;
    
    /* Create sensor data acquisition task */
    result = xTaskCreate(
        sensor_task,                    /* Task function */
        "SensorTask",                   /* Task name */
        MAIN_SENSOR_TASK_STACK_SIZE,     /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_SENSOR_TASK_PRIORITY,      /* Task priority */
        &s_sensor_task_handle);         /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create communication task */
    result = xTaskCreate(
        comm_task,                     /* Task function */
        "CommTask",                    /* Task name */
        MAIN_COMM_TASK_STACK_SIZE,       /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_COMM_TASK_PRIORITY,         /* Task priority */
        &s_comm_task_handle);          /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create storage task */
    result = xTaskCreate(
        storage_task,                   /* Task function */
        "StorageTask",                  /* Task name */
        MAIN_STORAGE_TASK_STACK_SIZE,    /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_STORAGE_TASK_PRIORITY,      /* Task priority */
        &s_storage_task_handle);        /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create OTA update task */
    result = xTaskCreate(
        update_task,                    /* Task function */
        "UpdateTask",                   /* Task name */
        MAIN_UPDATE_TASK_STACK_SIZE,     /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_UPDATE_TASK_PRIORITY,       /* Task priority */
        &s_update_task_handle);         /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create web interface task */
    result = xTaskCreate(
        web_interface_task,             /* Task function */
        "WebTask",                      /* Task name */
        MAIN_WEB_TASK_STACK_SIZE,       /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_WEB_TASK_PRIORITY,         /* Task priority */
        &s_web_task_handle);           /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create LED management task */
    result = xTaskCreate(
        led_task,                      /* Task function */
        "LedTask",                      /* Task name */
        MAIN_LED_TASK_STACK_SIZE,        /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_LED_TASK_PRIORITY,          /* Task priority */
        &s_led_task_handle);            /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    /* Create performance monitoring task */
    result = xTaskCreate(
        performance_task,               /* Task function */
        "PerfTask",                     /* Task name */
        MAIN_PERF_TASK_STACK_SIZE,       /* Stack size */
        NULL,                           /* Task parameter */
        MAIN_PERF_TASK_PRIORITY,         /* Task priority */
        &s_perf_task_handle);           /* Task handle */
    
    if (result != pdPASS) {
        return false;
    }
    
    return true;
}

/* ── Error Handling ───────────────────────────────────────────── */

/**
 * @brief Error handler with logging
 * @param pError Error description string
 */
static void main_error_handler(const char *const pError)
{
    /* In production, this would log to persistent storage */
    /* For now, just disable interrupts and halt */
    taskDISABLE_INTERRUPTS();
    
    /* Flash LED to indicate error */
    /* HAL_GPIO_TogglePin(ERROR_LED_GPIO_Port, ERROR_LED_Pin); */
    
    while (true) {
        /* Error loop - would implement watchdog reset in production */
        __NOP();
    }
}

/* ── System Initialization ───────────────────────────────────── */

/**
 * @brief Complete system initialization
 * @return true if successful, false otherwise
 */
static bool main_system_init(void)
{
    uint8_t retry_count = 0U;
    
    while (retry_count < MAIN_MAX_INIT_RETRIES) {
        /* Initialize hardware */
        if (!main_init_hardware()) {
            retry_count++;
            continue;
        }
        
        /* Initialize FreeRTOS objects */
        if (!main_init_freertos_objects()) {
            retry_count++;
            continue;
        }
        
        /* Initialize sensor subsystem */
        if (!sensor_init()) {
            retry_count++;
            continue;
        }
        
        /* Initialize web interface */
        if (!web_interface_init()) {
            retry_count++;
            continue;
        }
        
        /* All initialization successful */
        s_system_initialized = true;
        return true;
    }
    
    main_error_handler("System initialization failed after retries");
    return false;
}

/* ── Application Entry Point ───────────────────────────────────── */

/**
 * @brief Main application entry point
 * @return Should never return
 */
int main(void)
{
    /* Initialize system */
    if (!main_system_init()) {
        /* Error handler will be called from system_init */
        return -1;
    }
    
    /* Small delay to ensure all peripherals are ready */
    HAL_Delay(MAIN_STARTUP_DELAY_MS);
    
    /* Create application tasks */
    if (!main_create_tasks()) {
        /* Error handler will be called from create_tasks */
        return -1;
    }
    
    /* Start the scheduler */
    main_start_scheduler();
    
    /* Should never reach here */
    return 0;
}

/**
 * @brief Start FreeRTOS scheduler
 */
static void main_start_scheduler(void)
{
    /* Start the scheduler - this function should not return */
    vTaskStartScheduler();
    
    /* If we reach here, there was an error starting the scheduler */
    main_error_handler("Scheduler start failed");
}

/* ── Resource Cleanup ───────────────────────────────────────── */

/**
 * @brief Clean up system resources
 * 
 * This function is called during graceful shutdown or error recovery.
 */
static void main_cleanup_resources(void)
{
    /* Delete tasks if they exist */
    if (s_sensor_task_handle != NULL) {
        vTaskDelete(s_sensor_task_handle);
        s_sensor_task_handle = NULL;
    }
    
    if (s_web_task_handle != NULL) {
        vTaskDelete(s_web_task_handle);
        s_web_task_handle = NULL;
    }
    
    /* Delete FreeRTOS objects */
    if (s_sensor_queue != NULL) {
        vQueueDelete(s_sensor_queue);
        s_sensor_queue = NULL;
    }
    
    if (s_uart_rx_queue != NULL) {
        vQueueDelete(s_uart_rx_queue);
        s_uart_rx_queue = NULL;
    }
    
    if (s_uart_mutex != NULL) {
        vSemaphoreDelete(s_uart_mutex);
        s_uart_mutex = NULL;
    }
    
    s_system_initialized = false;
}

/* ── External Accessors (for other modules) ─────────────────────── */

/**
 * @brief Get sensor queue handle
 * @return Sensor queue handle
 */
QueueHandle_t get_sensor_queue(void)
{
    return s_sensor_queue;
}

/**
 * @brief Get UART receive queue handle
 * @return UART queue handle
 */
QueueHandle_t get_uart_rx_queue(void)
{
    return s_uart_rx_queue;
}

/**
 * @brief Get UART mutex handle
 * @return UART mutex handle
 */
SemaphoreHandle_t get_uart_mutex(void)
{
    return s_uart_mutex;
}

/**
 * @brief Check if system is initialized
 * @return true if initialized, false otherwise
 */
bool is_system_initialized(void)
{
    return s_system_initialized;
}

/* ── Callback Functions ───────────────────────────────────────── */

/**
 * @brief System Clock Configuration
 * 
 * This function configures the system clock to 168MHz.
 * In production, this would be generated by STM32CubeMX.
 */
void SystemClock_Config(void)
{
    /* System clock configuration would go here */
    /* This is typically generated by STM32CubeMX */
    
    /* Example configuration for STM32F4xx */
    /*
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Configure the main internal regulator output voltage
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    // Initialize the RCC Oscillators
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 8;
    RCC_OscInitStruct.PLL.PLLN = 336;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 7;
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    // Initialize the CPU, AHB and APB buses clocks
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5);
    */
}

/**
 * @brief This function handles System tick timer interrupt
 */
void SysTick_Handler(void)
{
    HAL_IncTick();
}

/**
 * @brief This function handles Hard fault interrupt
 */
void HardFault_Handler(void)
{
    main_error_handler("Hard Fault");
}

/**
 * @brief This function handles Memory management fault
 */
void MemManage_Handler(void)
{
    main_error_handler("Memory Management Fault");
}

/**
 * @brief This function handles Pre-fetch fault, memory access fault
 */
void BusFault_Handler(void)
{
    main_error_handler("Bus Fault");
}

/**
 * @brief This function handles Undefined instruction or illegal state
 */
void UsageFault_Handler(void)
{
    main_error_handler("Usage Fault");
}

/**
 * @brief This function handles Debug monitor interrupt
 */
void DebugMon_Handler(void)
{
    /* Empty handler */
}

/* ── Timing-Sensitive Regions (requires manual review) ───────────── */

/**
 * @note The following regions require manual review:
 * 
 * 1. System clock configuration timing - verify PLL settings
 * 2. HAL initialization timing - ensure proper sequence
 * 3. Task stack sizes - verify with high-water mark monitoring
 * 4. Queue depths - verify sufficient for worst-case scenarios
 * 5. Interrupt priorities - verify FreeRTOS API compatibility
 * 
 * <REVIEW_REQUIRED>
 * - System clock configuration and PLL settings
 * - HAL peripheral initialization sequence
 * - Task stack size verification with HWM monitoring
 * - Queue overflow handling strategy
 * - Interrupt priority assignments (NVIC_SetPriority)
 * - DMA buffer alignment and cache coherency (if used)
 * </REVIEW_REQUIRED>
 */
